export enum userQuoteTypes {
    FETCH_USER_QUOTE_REQUEST = "FETCH_USER_QUOTE_REQUEST",
    FETCH_USER_QUOTE_SUCCESS = "FETCH_USER_QUOTE_SUCCESS",
    FETCH_USER_QUOTE_FAILURE = "FETCH_USER_QUOTE_FAILURE"
  }
  