export enum usersTypes {
    FETCH_USER_REQUEST = "FETCH_USER_REQUEST",
    FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS",
    FETCH_USER_FAILURE = "FETCH_USER_FAILURE"
  }
  
  export enum userDetailTypes {
    FETCH_USER_DETAIL_REQUEST = "FETCH_USER_DETAIL_REQUEST",
    FETCH_USER_DETAIL_SUCCESS = "FETCH_USER_DETAIL_SUCCESS",
    FETCH_USER_DETAIL_FAILURE = "FETCH_USER_DETAIL_FAILURE"
  }
  